apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui
  labels:
    app: chat-ui
spec:
  selector:
    matchLabels:
      app: chat-ui
      tier: web
  template:
    metadata:
      labels:
        app: chat-ui
        tier: web
    spec:
      containers:
      - name: k8sdemo-chat-ui
        image: gcr.io/kochava-testing/k8sdemo-chat-ui:latest
        command: ["nginx-debug"]
        args: ["-g", "daemon off;"]
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 1500
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: chat-ui-nodeport
  labels:
    app: chat-ui
spec:
  type: NodePort
  selector:
    app: chat-ui
    tier: web
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.global-static-ip-name: "k8s-demo-chat-ui"
  name: k8s-demo-lb
  labels:
    app: chat-ui
spec:
  backend:
    serviceName: chat-ui-nodeport
    servicePort: 80