apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: chat-server-backend
spec:
  timeoutSec: 86400
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "CLIENT_IP"