apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.global-static-ip-name: "k8s-demo-chat-ui"
  name: k8s-demo-lb
  labels:
    app: chat-ui
spec:
  backend:
    serviceName: chat-ui-nodeport
    servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.global-static-ip-name: "k8s-demo-chat-server"
  name: k8s-demo-server-lb
  labels:
    app: chat-server
spec:
  backend:
    serviceName: chat-server-nodeport
    servicePort: 8080